import Foundation

public enum SocialPlatform: String, Codable, CaseIterable, Sendable { case x, bluesky, instagram, facebook, reddit, threads, snapchat, linkedin, mastodon }
public enum ActivityKind: String, Codable, Sendable { case mention, reply, message, reaction, follow, community, system }

public struct SocialAccount: Identifiable, Codable, Hashable, Sendable {
 public let id: UUID; public var platform: SocialPlatform; public var username: String; public var displayName: String; public var group: String; public var isEnabled: Bool
 public init(id: UUID = UUID(), platform: SocialPlatform, username: String, displayName: String, group: String = "Personal", isEnabled: Bool = true) { self.id=id; self.platform=platform; self.username=username; self.displayName=displayName; self.group=group; self.isEnabled=isEnabled }
}
public struct SocialActivity: Identifiable, Codable, Hashable, Sendable {
 public let id: UUID; public var accountID: UUID; public var platform: SocialPlatform; public var kind: ActivityKind; public var actor: String; public var body: String; public var createdAt: Date; public var isRead: Bool; public var priority: Int
 public init(id: UUID = UUID(), accountID: UUID, platform: SocialPlatform, kind: ActivityKind, actor: String, body: String, createdAt: Date = Date(), isRead: Bool = false, priority: Int = 0) { self.id=id; self.accountID=accountID; self.platform=platform; self.kind=kind; self.actor=actor; self.body=body; self.createdAt=createdAt; self.isRead=isRead; self.priority=priority }
}
public struct ProfileLink: Identifiable, Codable, Hashable, Sendable { public let id: UUID; public var accountID: UUID; public var platform: SocialPlatform; public var handle: String; public init(id:UUID=UUID(),accountID:UUID,platform:SocialPlatform,handle:String){self.id=id;self.accountID=accountID;self.platform=platform;self.handle=handle} }
public struct ConnectionPerson: Identifiable, Codable, Hashable, Sendable { public let id: UUID; public var name: String; public var notes: String; public var tags: Set<String>; public var links:[ProfileLink]; public init(id:UUID=UUID(),name:String,notes:String="",tags:Set<String>=[],links:[ProfileLink]=[]){self.id=id;self.name=name;self.notes=notes;self.tags=tags;self.links=links} }
public struct ComposerDraft: Identifiable, Codable, Hashable, Sendable { public let id:UUID; public var text:String; public var destinations:Set<UUID>; public var createdAt:Date; public var scheduledAt:Date?; public init(id:UUID=UUID(),text:String,destinations:Set<UUID>,createdAt:Date=Date(),scheduledAt:Date?=nil){self.id=id;self.text=text;self.destinations=destinations;self.createdAt=createdAt;self.scheduledAt=scheduledAt} }
public struct PublicationPlan: Identifiable, Equatable, Sendable { public let id:UUID; public var draftID:UUID; public var accountID:UUID; public var platform:SocialPlatform; public var text:String; public init(id:UUID=UUID(),draftID:UUID,accountID:UUID,platform:SocialPlatform,text:String){self.id=id;self.draftID=draftID;self.accountID=accountID;self.platform=platform;self.text=text} }
public enum ComposerError: Error, Equatable, Sendable { case noDestinations, emptyContent, unknownAccount(UUID), disabledAccount(UUID), limit(platform:SocialPlatform,maximum:Int,actual:Int) }
public struct ConnectionsSnapshot: Codable, Equatable, Sendable { public var accounts:[SocialAccount]; public var activities:[SocialActivity]; public var people:[ConnectionPerson]; public var drafts:[ComposerDraft] }

public actor ConnectionsCoordinator {
 private var accounts:[UUID:SocialAccount]; private var activities:[UUID:SocialActivity]; private var people:[UUID:ConnectionPerson]; private var drafts:[UUID:ComposerDraft]
 public init(accounts:[SocialAccount]=[],activities:[SocialActivity]=[],people:[ConnectionPerson]=[],drafts:[ComposerDraft]=[]){self.accounts = .init(uniqueKeysWithValues:accounts.map{($0.id,$0)});self.activities = .init(uniqueKeysWithValues:activities.map{($0.id,$0)});self.people = .init(uniqueKeysWithValues:people.map{($0.id,$0)});self.drafts = .init(uniqueKeysWithValues:drafts.map{($0.id,$0)})}
 public func accountList(platform:SocialPlatform?=nil)->[SocialAccount]{accounts.values.filter{platform == nil || $0.platform == platform!}.sorted{$0.displayName<$1.displayName}}
 public func ingest(_ value:SocialActivity)throws{guard accounts[value.accountID] != nil else{throw ComposerError.unknownAccount(value.accountID)};activities[value.id]=value}
 public func activityStream(unreadOnly:Bool=false)->[SocialActivity]{activities.values.filter{!unreadOnly || !$0.isRead}.sorted{$0.priority == $1.priority ? $0.createdAt > $1.createdAt : $0.priority > $1.priority}}
 public func searchPeople(_ query:String)->[ConnectionPerson]{let q=query.trimmingCharacters(in:.whitespacesAndNewlines);return people.values.filter{q.isEmpty || $0.name.localizedCaseInsensitiveContains(q) || $0.notes.localizedCaseInsensitiveContains(q) || $0.tags.contains(where:{$0.localizedCaseInsensitiveContains(q)}) || $0.links.contains(where:{$0.handle.localizedCaseInsensitiveContains(q)})}.sorted{$0.name<$1.name}}
 public func publicationPlans(for id:UUID)throws->[PublicationPlan]{guard let d=drafts[id] else{return[]};guard !d.destinations.isEmpty else{throw ComposerError.noDestinations};guard !d.text.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty else{throw ComposerError.emptyContent};return try d.destinations.map{aid in guard let a=accounts[aid] else{throw ComposerError.unknownAccount(aid)};guard a.isEnabled else{throw ComposerError.disabledAccount(aid)};let max:Int? = switch a.platform{case .x:280;case .bluesky:300;case .threads,.mastodon:500;case .instagram:2200;case .linkedin:3000;case .facebook:63206;case .reddit:40000;default:nil};if let max,d.text.count>max{throw ComposerError.limit(platform:a.platform,maximum:max,actual:d.text.count)};return .init(draftID:d.id,accountID:a.id,platform:a.platform,text:d.text)}.sorted{$0.platform.rawValue<$1.platform.rawValue}}
 public func snapshot()->ConnectionsSnapshot{.init(accounts:Array(accounts.values),activities:Array(activities.values),people:Array(people.values),drafts:Array(drafts.values))}
}
public actor ConnectionsStore { private let url:URL; public init(url:URL){self.url=url}; public func save(_ s:ConnectionsSnapshot)throws{let e=JSONEncoder();e.dateEncodingStrategy = .millisecondsSince1970;try FileManager.default.createDirectory(at:url.deletingLastPathComponent(),withIntermediateDirectories:true);try e.encode(s).write(to:url,options:.atomic)};public func load()throws->ConnectionsSnapshot{guard FileManager.default.fileExists(atPath:url.path) else{return .init(accounts:[],activities:[],people:[],drafts:[])};let d=JSONDecoder();d.dateDecodingStrategy = .millisecondsSince1970;return try d.decode(ConnectionsSnapshot.self,from:Data(contentsOf:url))}}
