import Foundation
import Testing
@testable import ConnectionsCore
@Test func multipleAccounts() async { let a=SocialAccount(platform:.instagram,username:"a",displayName:"A");let b=SocialAccount(platform:.instagram,username:"b",displayName:"B");let c=ConnectionsCoordinator(accounts:[a,b]);#expect(await c.accountList(platform:.instagram).count==2) }
@Test func priorityOrdering() async throws { let a=SocialAccount(platform:.x,username:"a",displayName:"A");let c=ConnectionsCoordinator(accounts:[a]);let high=SocialActivity(accountID:a.id,platform:.x,kind:.mention,actor:"A",body:"H",createdAt:.init(timeIntervalSince1970:1),priority:9);let low=SocialActivity(accountID:a.id,platform:.x,kind:.reply,actor:"B",body:"L",createdAt:.init(timeIntervalSince1970:2),priority:1);try await c.ingest(low);try await c.ingest(high);#expect(await c.activityStream().map(\.id)==[high.id,low.id]) }
@Test func publicationPlans() async throws { let a=SocialAccount(platform:.x,username:"a",displayName:"A");let b=SocialAccount(platform:.bluesky,username:"b",displayName:"B");let d=ComposerDraft(text:"Dreaming art into reality.",destinations:[a.id,b.id]);let c=ConnectionsCoordinator(accounts:[a,b],drafts:[d]);#expect(try await c.publicationPlans(for:d.id).count==2) }
@Test func xLimit() async { let a=SocialAccount(platform:.x,username:"a",displayName:"A");let d=ComposerDraft(text:String(repeating:"a",count:281),destinations:[a.id]);let c=ConnectionsCoordinator(accounts:[a],drafts:[d]);await #expect(throws:ComposerError.limit(platform:.x,maximum:280,actual:281)){try await c.publicationPlans(for:d.id)} }
@Test func peopleSearch() async { let a=SocialAccount(platform:.threads,username:"a",displayName:"A");let p=ConnectionPerson(name:"Corey",tags:["creator"],links:[.init(accountID:a.id,platform:.threads,handle:"@corey")]);let c=ConnectionsCoordinator(accounts:[a],people:[p]);#expect(await c.searchPeople("creator").count==1);#expect(await c.searchPeople("@corey").count==1) }
@Test func persistence() async throws { let date=Date(timeIntervalSince1970:1234.567);let a=SocialAccount(platform:.bluesky,username:"a",displayName:"A");let v=SocialActivity(accountID:a.id,platform:.bluesky,kind:.mention,actor:"A",body:"Hi",createdAt:date);let s=ConnectionsSnapshot(accounts:[a],activities:[v],people:[],drafts:[]);let u=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString).appendingPathComponent("c.json");let store=ConnectionsStore(url:u);try await store.save(s);#expect(try await store.load()==s) }
